apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 30090  # Choose a port between 30000-32767
  selector:
    app: mealie
  type: LoadBalancer
 
